"""`legit-edge pin {datasets,models <tier>}`"""
from __future__ import annotations
import json
import random
from pathlib import Path
import typer
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, BarColumn, TextColumn
import yaml
import requests
from datasets import load_dataset
from huggingface_hub import hf_hub_download

from ..paths import CONFIGS_DIR, DATA_DIR
from ..config import load_tiers, load_models
from ..multiturn_tasks import generate_multiturn_tasks
from .ollama_pull import pull_model

pin_app = typer.Typer(help="Pin model artifacts (Ollama) and workload subsets.")
console = Console()


def run_dataset_pin() -> None:
    """Reproduces the old scripts/01_pin_datasets.py logic, but uses paths.py."""
    random.seed(42)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    cfg = yaml.safe_load((CONFIGS_DIR / "workloads.yaml").read_text())["workloads"]

    def freeze(name: str, items: list[dict], n: int) -> None:
        sampled = random.sample(items, n) if len(items) > n else items
        out = DATA_DIR / f"{name}.jsonl"
        with out.open("w", encoding="utf-8") as f:
            for it in sampled:
                f.write(json.dumps(it) + "\n")
        console.print(f"  -> {out.name} ({len(sampled)} items)")

    m = cfg["math_gsm8k_hard"]
    ds = load_dataset(m["hf_id"], split=m["split"])
    freeze("math_standard", list(ds), m["n_standard"])
    freeze("math_megaquick", list(ds), m["n_megaquick"])

    b = cfg["reasoning_bbh"]
    all_bbh: list[dict] = []
    for sub in b["subtasks"]:
        all_bbh.extend(list(load_dataset(b["hf_id"], sub, split="test")))
    freeze("reasoning_standard", all_bbh, sum([b["n_per_subtask"]] * 3))
    freeze("reasoning_megaquick", all_bbh, b["n_megaquick"])

    t = cfg["tooluse_bfcl"]
    all_bfcl: list[dict] = []
    for fname in t["live_files"]:
        p = Path(hf_hub_download(repo_id=t["hf_id"], filename=fname, repo_type="dataset"))
        content = p.read_text(encoding="utf-8").strip()
        items = json.loads(content) if content.startswith("[") else [
            json.loads(line) for line in content.splitlines() if line.strip()
        ]
        all_bfcl.extend(items)
    freeze("tooluse_standard", all_bfcl, t["n_standard"])
    freeze("tooluse_megaquick", all_bfcl, t["n_megaquick"])

    # Fetch BFCL v4 ground-truth for the live_simple category (used by ToolUseWorkload.score).
    # The GT file maps question IDs to accepted function calls; after f15e39e+c4cdf92 the
    # tooluse pool is live_simple only, giving 100% GT coverage. This fetch is idempotent
    # via the `if not gt_out.exists()` guard below.
    gt_url = (
        "https://raw.githubusercontent.com/ShishirPatil/gorilla/main"
        "/berkeley-function-call-leaderboard/bfcl_eval/data/possible_answer"
        "/BFCL_v4_live_simple.json"
    )
    gt_out = DATA_DIR / "tooluse_ground_truth.jsonl"
    if not gt_out.exists():
        resp = requests.get(gt_url, timeout=30)
        resp.raise_for_status()
        gt_out.write_bytes(resp.content)
        console.print(f"  -> tooluse_ground_truth.jsonl ({gt_out.stat().st_size} bytes)")

    # Bespoke multi-step tool-use (Path B). Fully deterministic + offline: the pool is
    # author-generated by generate_multiturn_tasks(seed=42), then frozen to the seed-42
    # standard / mega-quick subsets via the same freeze() helper as the other workloads.
    mt = cfg["tooluse_mt"]
    mt_pool = generate_multiturn_tasks(mt["n_pool"], seed=42)
    freeze("tooluse_mt_standard", mt_pool, mt["n_standard"])
    freeze("tooluse_mt_megaquick", mt_pool, mt["n_megaquick"])


@pin_app.command("datasets")
def pin_datasets() -> None:
    """Pin GSM8K-Hard / BBH / BFCL v3 live_simple subset with seed=42."""
    console.print("Pinning workload subsets...")
    run_dataset_pin()
    console.print("Done.")


@pin_app.command("models")
def pin_models(tier: str) -> None:
    """Pull Ollama models onto a tier via HTTP /api/pull."""
    tiers = load_tiers()
    if tier not in tiers:
        console.print(f"[red]Unknown tier '{tier}'. Available: {list(tiers)}[/red]")
        raise typer.Exit(code=2)
    base_url = tiers[tier].base_url
    models = load_models()
    console.print(f"Pulling {len(models)} models onto [bold]{tier}[/] ({base_url}):")
    for name, m in models.items():
        tag = m.ollama_tag[tier]
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            TextColumn("{task.percentage:>3.0f}%"),
            console=console,
        ) as prog:
            task_id = prog.add_task(f"{tag}", total=100)
            for ev in pull_model(base_url, tag):
                status = ev.get("status", "")
                if "total" in ev and ev.get("total"):
                    prog.update(
                        task_id, total=ev["total"], completed=ev.get("completed", 0),
                        description=f"{tag}  [{status}]",
                    )
                else:
                    prog.update(task_id, description=f"{tag}  [{status}]")
            prog.update(task_id, completed=prog.tasks[0].total or 100)
    console.print("Done.")
